var appletsAlfaMenu = [
       
    { 'Events': [
        { 'on Page': [
            { 'on_ready - page is built': { frm: 'events-submit-cancel' } },
            { 'on_open - page is in viewport': { frm: 'events-submit-cancel' } },
            { 'on_cancel - button handler': { frm: 'events-submit-cancel', disabled:true}  },
            { 'on_sections_created': {disabled:true} }
        ]},
        { 'on Section': [
            { 'on_active': { frm: 'events-submit-cancel' } },
            { 'on_submit': { frm: 'events-submit-cancel' } },
            { 'on_cancel': { frm: 'events-submit-cancel' } },
            { 'on_before_cancel': { frm: 'events-submit-cancel', params:{ action: {goto_page: 'page3'} } } },
            { 'on_after_cancel': { frm: 'events-submit-cancel', params:{ action: {goto_page: 'page3'} } } },
        ]},
        { 'on Transaction': [
            { 'on_response': { frm:  'action-transaction-on-load'} },
            { 'on_error': { frm:  'action-transaction-on-load'} },
            { 'on_response with dsPage.CONFIRM_CANCEL': { frm:'action-transaction-confirm'} },
        ]},
    ]},
    { 'Actions': [
        { 'on SECTIONS':[
            { 'section_clear': { frm: 'alfa-checkbox' } },
            { 'section_hide': { frm: 'scanner-test' } },
            { 'goto_section': { frm: 'section-goto' } },
            { 'next_section': { frm: 'alfa-section' } },
            { 'section_reset_validation': {}},
        ]},
        { 'on PAGES':[
            { 'goto_page': { frm: 'action-goto_page' } },
            { 'goto_calling_page': { frm: 'action-goto_page' } },
            { 'goto_calling_page (imported)': { frm: 'aa-import-common' } },
            { 'footer_button': { frm: 'footer-buttons' } },
        ]},
        { 'goto-somewhere':[
            { 'goto_field': { frm: 'section-goto' } },
            { 'goto_section': { frm: 'section-goto' } },
            { 'next_section': { frm: 'section-goto' } },
            { 'goto_page': { frm: 'action-goto_page' } },
            { 'Navigation between Pages': [
                { 'goto_page': { frm: 'action-goto_page' } },
                { 'goto_calling_page': { frm: 'action-goto_page' } },
            ]},
            // { 'goto_calling_page': { frm: 'action-goto_page' } },
            // { 'goto_calling_page (imported)': { frm: 'aa-import-common' } },
            { 'goto_applet': { frm: 'action-goto_applet' } },
            { 'Navigation between Applets': [
                { 'reload_applet': { frm: 'action-goto_applet' } },
                { 'goto_applet': { frm: 'action-goto_applet' } },
                { 'goto_calling_applet': { frm: 'action-goto_applet' } },
                { 'goto_previous_applet': { frm: 'action-goto_applet' } },
                { 'goto_previous_or_menu <small style="color:red">deprecated</small>': { frm: 'action-goto_applet' } },
                { 'goto_applets_menu': { frm: 'action-goto_applet' } },           
            ]},
            // { 'goto_calling_applet': { frm: 'action-goto_applet' } },
            // { 'goto_previous_applet': { frm: 'action-goto_applet' } },
            { 'goto_previous_or_menu <small style="color:red">deprecated</small>': { frm: 'action-goto_previous_or_menu' } },
            { 'goto_applets_menu': { frm: 'action-goto_applet' } },
            { 'reload_applet': { frm: 'action-goto_applet', params:{ action: {goto_page: 'page2'} } }},
        ]},
        { 'transaction': [
            { 'on page load': { frm: 'action-transaction-on-load' } },
            { 'on submit': { frm: 'action-transaction-on-submit' } },
            { 'two async (simultaneous)': { frm: 'action-transactions-async' } },
            { 'two chained (one after another)': { frm: 'action-transactions-chained' } },
            { 'request PARAMs': [
                { 'request_params': {disabled:'true'}},
                { 'request_params_byvalue': {disabled:'true'}},
            ]},
        ]},
        // { 'goto (section, page, applet), next': { frm: 'actions-go' } },
        { 'run_function': { frm: 'action-run_function' } },
        
        { 'condition_if': [
            { 'is_true   <small style="color:blue"> boolean ===</small>':  { frm: 'action-condition' } },
            { 'is_truthy <small style="color:blue"> any ==</small>':  { frm: 'action-condition' } },
            { 'is_true_bool_by_path':  { frm: 'action-condition' } },
            { 'is_equal': { frm: 'action-condition' } },
            { 'is_equal_by_path': { frm: 'action-condition' } },
            { 'is_equal_numeric_by_path': { frm: 'action-condition' } },
            { 'is_empty': { frm: 'action-condition' } },
            { 'is_zero':  { frm: 'action-condition' } },
        ]  },
        // { 'Enable/Disable fields': { frm: 'actions-able_fields' } },
        // { 'data_elem commands': { frm: 'actions-data_element-cmd' } },
        // { 'row2array', disabled:true: { frm: 'actions-row2array' } },
        { 'console_log': [
            { 'console_log': { frm: 'action-console_log' } },
            { 'console_log_value': { frm: 'action-console_log' } },
            { 'console_log_value_async - <small style="color:blue">for testing</small>': { frm: 'action-foreach' } },
        ]},
        { 'set/assign/delete values': [
            { 'set_values <small style="color:blue">path: value</small>': { frm: 'action-set_values' } },
            { 'set_values with JSON': { frm: 'action-set_values', params:{ action: {goto_page: 'page3'} } } },
            { 'assign_byvalue  <small style="color:blue">path1: path2</small>': { frm: 'action-set_values', params:{ action: {goto_page: 'page2'} } } },
            { 'delete_values': { frm: 'data-binding' } },
        ]},
        // { 'foreach': { frm: 'action-foreach' } }, - NOT supported
        { 'action-array': { frm: 'action-array' } },
        { 'foreach_sync': { frm: 'action-foreach' } },
        { 'popup_message': { frm: 'action-popup_message' } },
        { 'alfa_group_reset': { frm: 'alfa-group', params: {action: {goto_page: 'page5'}} } },
        { 'action from Main Menu': { frm: 'ds-app-one', params: {action: {goto_page: 'page3'}} } },
        
        
    ]},
    { 'Functions': [
        { 'concatenate( )':   { frm: 'imported-functions' } },
        { 'calculate( )':     { frm: 'imported-functions' } },
        { 'calculateBool( )': { frm: 'imported-functions' } },
        { 'calculate( ) with condition_if': { frm: 'action-condition' } },
        { 'lookupListRequest( )': { frm: 'fn-lookup-list-request' } },
        { '&#10094;alfa-table&#10095; functions': [
            { 'addRecord( )': { frm: 'alfa-table-generated' } },
            { 'removeSelectedRecord( )': { frm: 'alfa-table-generated' } },
            { 'updateSelectedRecord( )': { frm: 'alfa-table-generated' } },
            { 'foreachRow( )': { frm: 'alfa-table-generated', params: {action: {goto_page: 'page5'}} } },
        ]},
        { 'Rules': [
            { 'ruleString( )':   { frm: 'fn-rules' } },
            { 'ruleBoolean( )':   { frm: 'fn-rules' } },
            { 'ruleNumber( )':   { frm: 'fn-rules' } },
        ]},
        { 'arrayGetRow( )':   { frm: 'imported-functions', params: {action: {goto_page: 'page4'}} } },
        { 'arrayLengthGet( )':   {frm: 'imported-functions'   } },
        { 'deleteArray( )': { frm: 'imported-functions', params: {action: {goto_page: 'page5'}} } },
        { 'arrayPush( )': { frm: 'imported-functions', params: {action: {goto_page: 'page5'}} } },
        { 'foreachRow( )': { frm: 'alfa-table-generated', params: {action: {goto_page: 'page5'}} } },
    ]},
    { 'Commands (Footer and Menu)': [
        { 'Footer buttons': [
            { 'page_commands: [ ]   <small style="color:blue">static</small>': { frm: 'footer-buttons',   } },
            { 'applet_commands: [ ] <small style="color:blue">static</small>': { frm: 'footer-buttons',  } },
            { 'footer_elements: [ ] <small style="color:blue">with databinding</small>': { frm: 'footer-buttons', params: {action: {goto_page: 'page3'}} } },
        ] },
        
        { 'Commands (buttons and menu)': { frm: 'menu-commands' } },
        { 'footer_elements: [ ]': { frm: 'footer-elements' } },
    ]},
    
    { '&#10094;alfa-elements&#10095;': [
        { '&#10094;alfa-input&#10095;': [
            { '&#10094;alfa-input&#10095;': { frm: 'alfa-input' } },
            { '&#10094;alfa-input&#10095; <small style="color:blue">validation</small>': { frm: 'alfa-input-validation' } },
            { '&#10094;alfa-input&#10095; <small style="color:blue">validation in section</small>': { frm: 'alfa-section', params: {action: {goto_page: 'page2'}} } },
            { '&#10094;alfa-input&#10095; <small style="color:blue">field_id config</small>': { frm: 'alfa-input-attr' } },
            { '&#10094;alfa-input&#10095; <small style="color:blue">type</small>': { frm: 'alfa-input-type' } },
        ]},
        { '&#10094;alfa-textarea&#10095;': { frm: 'alfa-textarea' } },
        { '&#10094;alfa-span&#10095;': { frm: 'alfa-span' } },
        { '&#10094;alfa-pre&#10095; <small style="color:blue">for JSON</small>': { frm: 'alfa-pre' } },
        { '&#10094;alfa-table&#10095;': [
            { '&#10094;alfa-table&#10095;': { frm: 'alfa-table' } },
            { '&#10094;alfa-table&#10095; sorting': { frm: 'alfa-table-sort' } },
            { '&#10094;alfa-table&#10095; functions': [
                { 'addRecord()': { frm: 'alfa-table-generated' } },
                { 'removeSelectedRecord()': { frm: 'alfa-table-generated' } },
                { 'updateSelectedRecord()': { frm: 'alfa-table-generated' } },
            ]},
        ]},
        { '&#10094;alfa-lookup&#10095;': { frm: 'alfa-lookup' } },
        { '&#10094;alfa-lookup&#10095; lookupListRequest()': { frm: 'fn-lookup-list-request' } },
        { '&#10094;alfa-button&#10095;': { frm: 'alfa-button' } },
        { '&#10094;alfa-progress&#10095;': { frm: 'alfa-progress' } },
        { '&#10094;alfa-progress&#10095; with foreach_sync': { frm: 'action-foreach' } },
        { '&#10094;alfa-checkbox&#10095;': { frm: 'alfa-checkbox' } },
        { '&#10094;alfa-group&#10095;': { frm: 'alfa-group' }, },
        { 'Styling alfa-elements with CSS': [
            { 'css <small style="color:blue">the <s>data_elem</s> data html CSS</small>':  { frm: 'alfa-element-css' }},
            { 'labelCss <small style="color:blue">label of data_elem CSS</small>':  { frm: 'alfa-element-css' }},
            { 'wrapperCss <small style="color:blue">wrapper: chevron, data_elem, required star</small>':  { frm: 'alfa-button', params: {action: {goto_page: 'page2'}} }},
            { 'rowCss <small style="color:blue">row: entire line width</small>':  { frm: 'alfa-button', params: {action: {goto_page: 'page2'}} }},
        ]},
        { 'alfa-elements HTML content': [
            { 'fixed_value':{}},
            { 'inner_text':{}},
            { 'inner_html':{}},
        ] },
        
    ]},
    { '&#10094;alfa-containers&#10095;': [
        { '&#10094;alfa-section&#10095;': { frm: 'alfa-section' }, },
        { '&#10094;alfa-section&#10095; focus': { frm: 'section-focus' }, },
        { '&#10094;alfa-section&#10095; validation': { frm: 'alfa-section', params: {action: {goto_page: 'page2'}} } },
        { '&#10094;alfa-group&#10095;': { frm: 'alfa-group' }, },
        { 'footer_elements: [ ]': { frm: 'footer-elements' } },
        { 'dt-rows: [ ] <span style="color:blue">CSS examples</span>': { frm: 'dt-rows' }, },

    ]},
    { 'Data Source scope': [
        { 'dsPage': { frm: 'ds-app-one' } },
        { 'dsApp':  { frm: 'ds-app-one' } },
        { 'dsGlob': { frm: 'ds-app-one' } },
        { 'dsConst': { frm: 'ds-app-one', params: {action: {goto_page: 'page4'}}  } },
        { 'pass params from Main Menu': { frm: 'ds-app-one', params: {fromMenu: 'param from menu'} } },
        { 'action from Main Menu': { frm: 'ds-app-one', params: {action: {goto_page: 'page3'}} } },
        { 'ds-app-two': { frm: 'ds-app-two' } },
    ]},
    { 'Data Binding path types': [
        { 'bound_path':{}},
        { 'bound_path_out':{}},
        { 'bound_path_disabled': { frm: 'alfa-input' }},
        { 'bound_path_disabled_onfalse': { frm: 'alfa-input' }   },
        { 'bound_path_hidden': { frm: 'alfa-input' }},
        { 'bound_path_hidden_onfalse': { frm: 'alfa-input' }   },
        { 'bound_path_required': { frm: 'alfa-input' }},
        { 'bound_path_decimal_scale <small style="color:blue">for numeric input</small>':{}},
        { 'bound_path_default':{}},
        { 'bound_path_reset_choice <small style="color:blue">for &lt;alfa-lookup&gt;</small>':{}},
        { 'bound_path_settings': {disabled:true   }},
        { 'bound_path_select_index <small style="color:blue">for &lt;alfa-table&gt;</small>':{}},
        { 'bound_path_cell_css     <small style="color:blue">for &lt;alfa-table&gt;</small>':{}},
        { 'bound_path_cell_html    <small style="color:blue">for &lt;alfa-table&gt;</small>':{}},
        { 'bound_path_css':{}},
    ]},
    { 'Importing pages, sections. etc': [
        { 'Importing from COMMON': { frm: 'importing-pages-sections'}  },
        { 'Importing from other-applet': { frm: 'importing-pages-sections2'}  },
        { 'other-applet used in example above': { frm: 'importing-other-applet'}  },
        { 'applet-with-common-pages': { frm: 'applet-with-common-pages'}  },
    ]},
    { 'Navigation between Applets': [
        { 'reload_applet': { frm: 'action-goto_applet' } },
        { 'goto_applet': { frm: 'action-goto_applet' } },
        { 'goto_calling_applet': { frm: 'action-goto_applet' } },
        { 'goto_previous_applet': { frm: 'action-goto_applet' } },
        { 'goto_previous_or_menu': { frm: 'action-goto_applet' } },
        { 'goto_applets_menu': { frm: 'action-goto_applet' } },           
    ]},
]

export default appletsAlfaMenu;